language: node_js
node_js:
  - '9'
  - '8'
  - '6'

install
  - yarn

script:
  - yarn test

after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npx semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email: false
