name: CI
on:
  pull_request:
    paths-ignore:
      - 'website/**'
  push:
    paths-ignore:
      - 'website/**'
jobs:
  test:
    name: Node ${{ matrix.node_version }} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [12, 14, 16]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('package.json') }}

      - name: Install
        run: yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
