name: Website
on: 
  push:
    branches:
      - master
jobs:
  Deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      
      - name: Install
        run: yarn
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      
      - name: ZEIT Now Deployment
        uses: amondnet/now-deployment@v2.0.1
        with:
          zeit-token: ${{ secrets.NOW_TOKEN }}
          now-args: '--prod'
