name: Website
on:
  push:
    paths:
      - 'website/**'
      - 'now.json'
      - 'github/workflows/website.yml'
    branches:
      - master
jobs:
  Deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    if: contains(github.actor, 'renovate') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: ZEIT Now Deployment
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.NOW_TOKEN }}
          vercel-args: '--prod'
          vercel-project-id: ${{ secrets.ZEIT_PROJECT }}
          vercel-org-id: ${{ secrets.ZEIT_ORG }}

      - name: Index Docs
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          file: algolia/config.json
